@echo off
echo Removing React Navigation packages and cleaning installation...
if exist node_modules rmdir /s /q node_modules
if exist package-lock.json del package-lock.json
echo Installing clean dependencies...
npm install
echo Building debug APK...
npx expo run:android --variant debug