@echo off
echo Removing incompatible dependency...
call npm uninstall react-native-worklets
echo Cleaning android folder...
if exist android rmdir /s /q android
echo Running prebuild...
call npx expo prebuild --platform android
echo Building APK...
cd android
call gradlew.bat assembleRelease
echo APK built at: android\app\build\outputs\apk\release\app-release.apk
pause