@echo off
echo Fixing Metro dependencies...
echo Removing node_modules...
if exist node_modules rmdir /s /q node_modules
if exist package-lock.json del package-lock.json
echo Installing compatible versions...
call npm install
echo Fixing Expo dependencies...
call npx expo install --fix
echo Building production APK...
call build-production.bat