@echo off
echo Fixing TypeScript build issues...
echo Removing node_modules...
if exist node_modules rmdir /s /q node_modules
echo Removing package-lock.json...
if exist package-lock.json del package-lock.json
echo Installing dependencies...
call npm install
echo Fixing Expo dependencies...
call npx expo install --fix
echo Running prebuild...
call npx expo prebuild --platform android
echo Build fix complete!
pause