@echo off
echo Fixing Metro bundling issues...
echo Clearing Metro cache...
call npx expo start --clear
timeout /t 3
taskkill /f /im node.exe 2>nul
echo Rebuilding with fixed Metro config...
call build-production.bat