import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    scrollContent: {
        paddingTop: 60,
        paddingHorizontal: 20,
        paddingBottom: 100,
        flexGrow: 1,
    },
    header: {
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 18,
        color: '#FFFFFF',
        marginBottom: 5,
    },
    headerSubDate: {
        fontSize: 15,
        color: '#FFFFFF',
    },
    headerSubtitle: {
        fontSize: 16,
        color: '#BFDBFE',
    },
    metricsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    metricCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 12,
        width: '48%',
        marginBottom: 8,
    },
    metricCardShadow: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    metricHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    metricTitle: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
        marginLeft: 8,
        flex: 1,
    },
    metricValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    balanceCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 25,
        marginBottom: 20,
        alignItems: 'center',
    },
    balanceCardShadow: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    balanceTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#6B7280',
        marginBottom: 10,
    },
    balanceAmount: {
        fontSize: 36,
        fontWeight: 'bold',
    },
    chartCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        marginBottom: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    chartCardShadow: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    chartTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 15,
        textAlign: 'center',
    },
    chartSwitcher: {
        flexDirection: 'row',
        marginBottom: 15,
        gap: 8,
        flexWrap: 'wrap',
    },
    chartTab: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        backgroundColor: '#F3F4F6',
    },
    chartTabActive: {
        backgroundColor: '#3B82F6',
    },
    chartTabText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    chartTabTextActive: {
        color: '#FFFFFF',
    },
    emptyChart: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyChartText: {
        fontSize: 14,
        color: '#9CA3AF',
        textAlign: 'center',
    },
    chartLegend: {
        marginTop: 10,
        paddingHorizontal: 10,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
        justifyContent: 'space-between',
    },
    legendLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    legendColor: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 8,
    },
    legendText: {
        fontSize: 12,
        color: '#374151',
        flex: 1,
    },
    legendValue: {
        fontSize: 12,
        fontWeight: '600',
        color: '#1F2937',
        marginLeft: 8,
    },
    legendPercent: {
        fontSize: 11,
        color: '#6B7280',
        marginLeft: 4,
    },
    comparisonBar: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 8,
    },
    comparisonLabel: {
        width: 80,
        fontSize: 12,
        color: '#374151',
        fontWeight: '600',
    },
    comparisonBarContainer: {
        flex: 1,
        height: 32,
        backgroundColor: '#F3F4F6',
        borderRadius: 8,
        overflow: 'hidden',
        marginHorizontal: 8,
    },
    comparisonBarFill: {
        height: '100%',
        justifyContent: 'center',
        paddingHorizontal: 8,
    },
    comparisonValue: {
        fontSize: 11,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    comparisonAmount: {
        width: 70,
        fontSize: 12,
        fontWeight: '600',
        color: '#1F2937',
        textAlign: 'right',
    },
    balanceIndicator: {
        marginTop: 12,
        padding: 12,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    balanceText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    goalBar: {
        marginVertical: 6,
    },
    goalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    goalName: {
        fontSize: 12,
        fontWeight: '600',
        color: '#374151',
        flex: 1,
    },
    goalProgress: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    goalProgressBar: {
        height: 24,
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        overflow: 'hidden',
    },
    goalProgressFill: {
        height: '100%',
        justifyContent: 'center',
        paddingHorizontal: 8,
    },
    goalProgressText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    healthMetrics: {
        marginTop: 12,
        padding: 12,
        backgroundColor: '#F9FAFB',
        borderRadius: 8,
    },
    healthMetricRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    healthMetricLabel: {
        fontSize: 12,
        color: '#6B7280',
    },
    healthMetricValue: {
        fontSize: 12,
        fontWeight: '600',
        color: '#1F2937',
    },
    healthRecommendation: {
        marginTop: 8,
        padding: 10,
        borderRadius: 6,
        backgroundColor: '#FFFFFF',
    },
    healthRecommendationText: {
        fontSize: 11,
        color: '#374151',
        lineHeight: 16,
    },
    healthScoreContainer: {
        alignItems: 'center',
        marginBottom: 16,
    },
    healthScoreCircle: {
        width: 120,
        height: 120,
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    healthScoreText: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    healthScoreLabel: {
        fontSize: 13,
        fontWeight: '600',
        marginTop: 4,
    },
    healthMetricsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 12,
        gap: 8,
    },
    healthMetricCard: {
        flex: 1,
        minWidth: '48%',
        backgroundColor: '#FFFFFF',
        padding: 12,
        borderRadius: 8,
        borderLeftWidth: 3,
    },
    healthMetricCardLabel: {
        fontSize: 11,
        color: '#6B7280',
        marginBottom: 4,
    },
    healthMetricCardValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    healthMetricCardPercent: {
        fontSize: 12,
        color: '#6B7280',
        marginTop: 2,
    },
    insightBadge: {
        marginTop: 12,
        padding: 10,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    insightBadgeText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#FFFFFF',
        marginLeft: 6,
        flex: 1,
    },
    interactiveLegendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        justifyContent: 'space-between',
        padding: 8,
        borderRadius: 6,
        backgroundColor: '#F9FAFB',
    },
    highlightedItem: {
        backgroundColor: '#FEF3C7',
        borderLeftWidth: 3,
        borderLeftColor: '#F59E0B',
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    settingsIcon: {
        marginLeft: 10,
    },
    iconsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    userIcon: {
        marginRight: 10,
    },
    buttonsContainer: {
        flexDirection: 'row',
        marginBottom: 20,
    },
    actionButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingTop: 10,
        paddingBottom: 10,
        flex: 1,
        marginHorizontal: 5,
        alignItems: 'center',
    },
    actionButtonShadow: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    actionButtonText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#1F2937',
    },
    soonBadge: {
        position: 'absolute',
        top: -6,
        right: -8,
        backgroundColor: '#F59E0B',
        borderRadius: 6,
        paddingHorizontal: 4,
        paddingVertical: 1,
        minWidth: 24,
    },
    soonBadgeText: {
        color: '#FFFFFF',
        fontSize: 10,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    goalsButton: {
        width: 80,
        flex: 0,
    },
    manageCategoriesButton: {
        width: 150,
        flex: 0,
    }
});